# Generated by Django 3.0.8 on 2020-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_ID', models.CharField(max_length=6)),
                ('Book_Name', models.CharField(max_length=100)),
                ('Author', models.CharField(default='', max_length=100)),
                ('Genre', models.CharField(choices=[('education', 'Education'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('dystopian', 'Dystopian'), ('science fiction', 'Science Fiction'), ('classics', 'Classics')], default='education', max_length=100)),
                ('Book_Publisher', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Not issued', 'Not issued'), ('Issued', 'Issued')], default='Not Issued', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
