# Generated by Django 3.0.8 on 2020-11-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_issued'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issued',
        ),
    ]
